import './js/modal/modal-mobile-menu';
import './js/slider';
import './js/recipes';
import './js/all-categories';
import './js/pagination';
import './js/popular';
import './js/modal/modal-recipe';
import './js/modal/modal-rating';
import './js/modal/modal-order';
import './js/jquery/backToTapBtn';
import './js/service/move-btn-range';
import './js/filter'
import './js/modal/rating-stars'